# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'earthdrill.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_earthquake_dialog(object):

    def setupUi(self, earthquake_dialog):
        earthquake_dialog.setObjectName("earthquake_dialog")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/ecelogo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        earthquake_dialog.setWindowIcon(icon)
        earthquake_dialog.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.verticalLayout = QtWidgets.QVBoxLayout(earthquake_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(earthquake_dialog)
        self.widget.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.gridLayout.addWidget(self.comboBox_1, 0, 1, 1, 1)
        self.pushButton1 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton1.setStyleSheet("background-color: rgb(226, 226, 226);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/sample/New folder/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton1.setIcon(icon1)
        self.pushButton1.setCheckable(False)
        self.pushButton1.setObjectName("pushButton1")
        self.gridLayout.addWidget(self.pushButton1, 0, 2, 1, 2)
        self.pushButton2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton2.setStyleSheet("background-color: rgb(226, 226, 226);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/sample/New folder/off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton2.setIcon(icon2)
        self.pushButton2.setObjectName("pushButton2")
        self.gridLayout.addWidget(self.pushButton2, 0, 4, 1, 2)
        self.toolButton_1 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_1.setStatusTip("")
        self.toolButton_1.setAccessibleDescription("")
        self.toolButton_1.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.toolButton_1.setObjectName("toolButton_1")
        self.gridLayout.addWidget(self.toolButton_1, 0, 6, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.widget_2)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.pushButton3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton3.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.pushButton3.setIcon(icon1)
        self.pushButton3.setObjectName("pushButton3")
        self.gridLayout.addWidget(self.pushButton3, 1, 2, 1, 2)
        self.pushButton4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton4.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.pushButton4.setIcon(icon2)
        self.pushButton4.setObjectName("pushButton4")
        self.gridLayout.addWidget(self.pushButton4, 1, 4, 1, 2)
        self.toolButton_2 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_2.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 1, 6, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.pushButton5 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton5.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.pushButton5.setIcon(icon1)
        self.pushButton5.setObjectName("pushButton5")
        self.gridLayout.addWidget(self.pushButton5, 2, 2, 1, 2)
        self.pushButton6 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton6.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.pushButton6.setIcon(icon2)
        self.pushButton6.setObjectName("pushButton6")
        self.gridLayout.addWidget(self.pushButton6, 2, 4, 1, 2)
        self.toolButton_3 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_3.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 2, 6, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget_2)
        self.plainTextEdit.setReadOnly(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 3, 0, 2, 3)
        self.splitter_2 = QtWidgets.QSplitter(self.widget_2)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label = QtWidgets.QLabel(self.splitter_2)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.splitter_2, 3, 3, 1, 2)
        self.splitter = QtWidgets.QSplitter(self.widget_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.pushButton7 = QtWidgets.QPushButton(self.splitter)
        self.pushButton7.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton7.setObjectName("pushButton7")
        self.pushButton8 = QtWidgets.QPushButton(self.splitter)
        self.pushButton8.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton8.setObjectName("pushButton8")
        self.gridLayout.addWidget(self.splitter, 3, 5, 2, 2)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.widget)
        self.retranslateUi(earthquake_dialog)
        self.buttonBox.accepted.connect(earthquake_dialog.accept)
        self.buttonBox.rejected.connect(earthquake_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(earthquake_dialog)

    def retranslateUi(self, earthquake_dialog):
        _translate = QtCore.QCoreApplication.translate
        earthquake_dialog.setWindowTitle(_translate("earthquake_dialog", "Earthquake Emergency Drill"))
        self.label_4.setText(_translate("earthquake_dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#ffd700;\">Earthquake Emergency Drill Interface</span></p></body></html>"))
        self.label_2.setText(_translate("earthquake_dialog", "Stream 1:"))
        self.comboBox_1.setItemText(0, _translate("earthquake_dialog", "Station 1"))
        self.comboBox_1.setItemText(1, _translate("earthquake_dialog", "Station 2"))
        self.comboBox_1.setItemText(2, _translate("earthquake_dialog", "Station 3"))
        self.pushButton1.setText(_translate("earthquake_dialog", "On"))
        self.pushButton2.setText(_translate("earthquake_dialog", "Off"))
        self.toolButton_1.setToolTip(_translate("earthquake_dialog", "Configure stream 1"))
        self.toolButton_1.setText(_translate("earthquake_dialog", "..."))
        self.label_1.setText(_translate("earthquake_dialog", "Stream 2:"))
        self.comboBox_2.setItemText(0, _translate("earthquake_dialog", "Station 1"))
        self.comboBox_2.setItemText(1, _translate("earthquake_dialog", "Station 2"))
        self.comboBox_2.setItemText(2, _translate("earthquake_dialog", "Station 3"))
        self.pushButton3.setText(_translate("earthquake_dialog", "On"))
        self.pushButton4.setText(_translate("earthquake_dialog", "Off"))
        self.toolButton_2.setToolTip(_translate("earthquake_dialog", "Configure stream 2"))
        self.toolButton_2.setText(_translate("earthquake_dialog", "..."))
        self.label_3.setText(_translate("earthquake_dialog", "Stream 3:"))
        self.comboBox_3.setItemText(0, _translate("earthquake_dialog", "Station 1"))
        self.comboBox_3.setItemText(1, _translate("earthquake_dialog", "Station 2"))
        self.comboBox_3.setItemText(2, _translate("earthquake_dialog", "Station 3"))
        self.pushButton5.setText(_translate("earthquake_dialog", "On"))
        self.pushButton6.setText(_translate("earthquake_dialog", "Off"))
        self.toolButton_3.setToolTip(_translate("earthquake_dialog", "Configure stream 3"))
        self.toolButton_3.setText(_translate("earthquake_dialog", "..."))
        self.plainTextEdit.setPlainText(_translate("earthquake_dialog", "Stream 1: \n"
"Stream 2:\n"
"Stream 3:\n"
"STATUS :"))
        self.label.setText(_translate("earthquake_dialog", "Select Alarm:"))
        self.comboBox.setItemText(0, _translate("earthquake_dialog", "Alarm_1"))
        self.comboBox.setItemText(1, _translate("earthquake_dialog", "Alarm_2"))
        self.comboBox.setItemText(2, _translate("earthquake_dialog", "Add more"))
        self.pushButton7.setText(_translate("earthquake_dialog", "PLAY"))
        self.pushButton8.setText(_translate("earthquake_dialog", "STOP"))
        self.label_5.setText(_translate("earthquake_dialog", "<html><head/><body><p>Playing time:</p><p><span style=\" color:#0000ff;\">00:00:00</span></p></body></html>"))
import resources.icons_rc
import resources.new_rc

