# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'liveannou2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_live_dialog(object):

    def setupUi(self, live_dialog):
        live_dialog.setObjectName("live_dialog")
        live_dialog.resize(383, 311)
        live_dialog.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/ecelogo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        live_dialog.setWindowIcon(icon)
        live_dialog.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(live_dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_1 = QtWidgets.QWidget(live_dialog)
        self.widget_1.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.widget_1.setObjectName("widget_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label1 = QtWidgets.QLabel(self.widget_1)
        self.label1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label1.setObjectName("label1")
        self.gridLayout_2.addWidget(self.label1, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget_1)
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label2 = QtWidgets.QLabel(self.widget_2)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 0, 0, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.gridLayout.addWidget(self.comboBox_1, 0, 1, 1, 1)
        self.pushButton1 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton1.setStyleSheet("background-color: rgb(226, 226, 226);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/sample/New folder/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton1.setIcon(icon1)
        self.pushButton1.setCheckable(True)
        self.pushButton1.setChecked(False)
        self.pushButton1.setDefault(False)
        self.pushButton1.setFlat(False)
        self.pushButton1.setObjectName("pushButton1")
        self.gridLayout.addWidget(self.pushButton1, 0, 2, 1, 2)
        self.pushButton2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton2.setStyleSheet("background-color: rgb(226, 226, 226);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/sample/New folder/off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton2.setIcon(icon2)
        self.pushButton2.setObjectName("pushButton2")
        self.gridLayout.addWidget(self.pushButton2, 0, 4, 1, 2)
        self.toolButton_1 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_1.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.toolButton_1.setObjectName("toolButton_1")
        self.gridLayout.addWidget(self.toolButton_1, 0, 6, 1, 1)
        self.label3 = QtWidgets.QLabel(self.widget_2)
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.pushButton3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton3.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.pushButton3.setIcon(icon1)
        self.pushButton3.setCheckable(True)
        self.pushButton3.setObjectName("pushButton3")
        self.gridLayout.addWidget(self.pushButton3, 1, 2, 1, 2)
        self.pushButton4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton4.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.pushButton4.setIcon(icon2)
        self.pushButton4.setObjectName("pushButton4")
        self.gridLayout.addWidget(self.pushButton4, 1, 4, 1, 2)
        self.toolButton_2 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_2.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 1, 6, 1, 1)
        self.label4 = QtWidgets.QLabel(self.widget_2)
        self.label4.setObjectName("label4")
        self.gridLayout.addWidget(self.label4, 2, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.pushButton5 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton5.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.pushButton5.setIcon(icon1)
        self.pushButton5.setCheckable(True)
        self.pushButton5.setObjectName("pushButton5")
        self.gridLayout.addWidget(self.pushButton5, 2, 2, 1, 2)
        self.pushButton6 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton6.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.pushButton6.setIcon(icon2)
        self.pushButton6.setObjectName("pushButton6")
        self.gridLayout.addWidget(self.pushButton6, 2, 4, 1, 2)
        self.toolButton_3 = QtWidgets.QToolButton(self.widget_2)
        self.toolButton_3.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 2, 6, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget_2)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 3, 0, 2, 3)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 3, 2, 2)
        self.pushButton7 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton7.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton7.setObjectName("pushButton7")
        self.gridLayout.addWidget(self.pushButton7, 3, 5, 1, 2)
        self.pushButton8 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton8.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton8.setObjectName("pushButton8")
        self.gridLayout.addWidget(self.pushButton8, 4, 5, 1, 2)
        self.gridLayout_2.addWidget(self.widget_2, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget_1)
        self.buttonBox.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_1)
        self.retranslateUi(live_dialog)
        self.buttonBox.accepted.connect(live_dialog.accept)
        self.buttonBox.rejected.connect(live_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(live_dialog)

    def retranslateUi(self, live_dialog):
        _translate = QtCore.QCoreApplication.translate
        live_dialog.setWindowTitle(_translate("live_dialog", "Live Announcement"))
        self.label1.setText(_translate("live_dialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#ffd700;\">Live Announcement Interface</span></p><p><span style=\" font-size:9pt;\"><br/></span></p></body></html>"))
        self.label2.setText(_translate("live_dialog", "Stream 1:"))
        self.comboBox_1.setItemText(0, _translate("live_dialog", "Station 1 - A"))
        self.comboBox_1.setItemText(1, _translate("live_dialog", "Station 1 - B"))
        self.comboBox_1.setItemText(2, _translate("live_dialog", "Station 1 - C"))
        self.pushButton1.setText(_translate("live_dialog", "On"))
        self.pushButton2.setText(_translate("live_dialog", "Off"))
        self.toolButton_1.setToolTip(_translate("live_dialog", "Configure stream 1"))
        self.toolButton_1.setText(_translate("live_dialog", "..."))
        self.label3.setText(_translate("live_dialog", "Stream 2:"))
        self.comboBox_2.setItemText(0, _translate("live_dialog", "Station 2 - A"))
        self.comboBox_2.setItemText(1, _translate("live_dialog", "Station 2 - B"))
        self.comboBox_2.setItemText(2, _translate("live_dialog", "Station 2 - C"))
        self.pushButton3.setText(_translate("live_dialog", "On"))
        self.pushButton4.setText(_translate("live_dialog", "Off"))
        self.toolButton_2.setToolTip(_translate("live_dialog", "Configure stream 2"))
        self.toolButton_2.setText(_translate("live_dialog", "..."))
        self.label4.setText(_translate("live_dialog", "Stream 3:"))
        self.comboBox_3.setItemText(0, _translate("live_dialog", "Station 3 - A"))
        self.comboBox_3.setItemText(1, _translate("live_dialog", "Station 3 - B"))
        self.comboBox_3.setItemText(2, _translate("live_dialog", "Station 3 -C"))
        self.pushButton5.setText(_translate("live_dialog", "On"))
        self.pushButton6.setText(_translate("live_dialog", "Off"))
        self.toolButton_3.setToolTip(_translate("live_dialog", "Configure stream 3"))
        self.toolButton_3.setText(_translate("live_dialog", "..."))
        self.plainTextEdit.setPlainText(_translate("live_dialog", "Stream 1: \n"
"Stream 2:\n"
"Stream 3:\n"
"STATUS :"))
        self.label_5.setText(_translate("live_dialog", "<html><head/><body><p>Record Time:</p><p><span style=\" color:#0000ff;\">00:00:00</span></p></body></html>"))
        self.pushButton7.setText(_translate("live_dialog", "PLAY"))
        self.pushButton8.setText(_translate("live_dialog", "STOP"))


